DOMAIN = "camilladsp"
NAME = "CamillaDSP"
VERSION = "1.0.1"

CONFIG_URL = "url"
CONFIG_VOLUME_MIN = "volume_min"
CONFIG_VOLUME_MAX = "volume_max"
CONFIG_VOLUME_STEP = "volume_step"

ATTR_VOLUME_DB = "volume_db"
ATTR_VOLUME_AUX1_DB = "volume_aux1_db"
ATTR_VOLUME_AUX2_DB = "volume_aux2_db"
ATTR_VOLUME_AUX3_DB = "volume_aux3_db"
ATTR_VOLUME_AUX4_DB = "volume_aux4_db"
ATTR_CAPTURE_RATE = "capturerate"
ATTR_MUTE = "is_fader_muted"
ATTR_MUTE_AUX1 = "is_aux1_muted"
ATTR_MUTE_AUX2 = "is_aux2_muted"
ATTR_MUTE_AUX3 = "is_aux3_muted"
ATTR_MUTE_AUX4 = "is_aux4_muted"
ATTR_FADER = "fader"
SERVICE_VOLUME_DB_SET = "volume_db_set"
SERVICE_FADER_MUTE = "fader_mute"
